# Generated by Django 3.1.2 on 2020-10-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=255)),
                ('teacherName', models.CharField(max_length=255)),
                ('documentType', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='documents/files')),
            ],
        ),
    ]
