# Generated by Django 3.1.2 on 2020-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/files', verbose_name='<b>Файл </b>'),
        ),
        migrations.AlterField(
            model_name='document',
            name='documentName',
            field=models.CharField(max_length=255, verbose_name='<b>Наименование модуля/дисциплины </b>'),
        ),
        migrations.AlterField(
            model_name='document',
            name='documentType',
            field=models.CharField(max_length=100, verbose_name='<b>Тип документа </b>'),
        ),
        migrations.AlterField(
            model_name='document',
            name='teacherName',
            field=models.CharField(max_length=255, verbose_name='<b>ФИО преподавателя </b>'),
        ),
    ]
