# Generated by Django 3.1.2 on 2020-10-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentName2',
            field=models.CharField(default=None, max_length=255, verbose_name='<b>Наименование дисциплины </b>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='documentName',
            field=models.CharField(max_length=255, verbose_name='<b>Наименование модуля </b>'),
        ),
    ]
