# Generated by Django 3.1.2 on 2020-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201030_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentName2',
            field=models.CharField(default=True, max_length=255, verbose_name='<b>Наименование дисциплины </b>'),
        ),
    ]
