# Generated by Django 3.1.5 on 2021-01-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201030_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentName2',
            field=models.CharField(default='', max_length=255, verbose_name='<b>Наименование дисциплины </b>'),
        ),
    ]
