# Generated by Django 3.1.5 on 2021-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210112_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cycleType',
            field=models.CharField(default='', max_length=255, verbose_name='<b>Наименование ПЦК </b>'),
        ),
        migrations.AddField(
            model_name='document',
            name='studyGroup',
            field=models.CharField(default='', max_length=255, verbose_name='<b>Группа </b>'),
        ),
    ]
