# Generated by Django 3.1.5 on 2021-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210113_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=255, verbose_name='<b>Специальность </b>')),
                ('qualification', models.CharField(default='', max_length=255, verbose_name='<b>Квалификация </b>')),
                ('group', models.CharField(default='', max_length=255, verbose_name='<b>Группа </b>')),
                ('student', models.CharField(default='', max_length=255, verbose_name='<b>ФИО студента </b>')),
                ('document', models.FileField(upload_to='documents/files', verbose_name='<b>Файл </b>')),
            ],
        ),
    ]
