# Generated by Django 3.1.5 on 2021-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_diplomadocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomadocument',
            name='theme',
            field=models.CharField(default='', max_length=255, verbose_name='<b>Тема дипломного проекта </b>'),
        ),
    ]
