# Generated by Django 3.1.5 on 2021-01-31 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_diplomadocument_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomadocument',
            name='postDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='diplomadocument',
            name='year',
            field=models.CharField(default='', max_length=100, verbose_name='<b>Учебный год </b>'),
        ),
        migrations.AddField(
            model_name='document',
            name='postDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(default='', max_length=100, verbose_name='<b>Учебный год </b>'),
        ),
    ]
