# Generated by Django 3.2.6 on 2021-09-01 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210131_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName21', models.CharField(max_length=255, verbose_name='<b>Наименование модуля </b>')),
                ('_documentName21', models.CharField(default='', max_length=255, verbose_name='<b>Наименование дисциплины </b>')),
                ('cycleType21', models.CharField(default='', max_length=255, verbose_name='<b>Наименование ПЦК </b>')),
                ('studyGroup21', models.CharField(default='', max_length=255, verbose_name='<b>Группа </b>')),
                ('teacherName21', models.CharField(max_length=255, verbose_name='<b>ФИО преподавателя </b>')),
                ('documentType21', models.CharField(max_length=100, verbose_name='<b>Тип документа </b>')),
                ('year21', models.CharField(default='', max_length=100, verbose_name='<b>Учебный год </b>')),
                ('postDate21', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('document21', models.FileField(upload_to='documents/files', verbose_name='<b>Файл </b>')),
            ],
        ),
    ]
