# Generated by Django 3.2.6 on 2021-09-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document21'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document21',
            old_name='_documentName21',
            new_name='docName21',
        ),
    ]
